name: smartkit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.1
  shimmer: ^1.1.2
  flutter_signin_button: ^1.1.0
  simple_animations: ^3.0.2
  flutter_staggered_grid_view: ^0.3.4
  titled_navigation_bar: ^4.1.0
  bubble_bottom_bar: ^1.2.0
  gradient_widgets: ^0.5.2
  carousel_slider: ^3.0.0
  url_launcher: ^6.0.2
  flutter_slidable: ^0.5.7
  universal_widget: ^1.2.5
  flutter_spinkit: ^5.0.0
  youtube_player_flutter: ^8.0.0
  # webview_flutter: ^2.0.2
  flare_dart: ^2.3.4
  flutter_speed_dial: ^3.0.5
  introduction_screen: ^2.0.0
  flutter_swiper: ^1.1.6
  intro_slider: ^2.3.4
  intro_views_flutter: ^2.8.2
  flutter_inappwebview: ^5.3.2
  connectivity: ^3.0.2
  flutter_web_browser: ^0.14.0
  font_awesome_flutter: ^8.11.0

  responsive_builder: ^0.4.1
 # ////////// SmartQuiz Packages //////////  
  curved_navigation_bar: ^0.3.7
  liquid_progress_indicator: 0.3.2
  # intl: ^0.17.0
  matrix4_transform: ^2.0.0



 # ////////// HappyShop Packages //////////  

  country_code_picker: ^2.0.1
  like_button: ^2.0.1
  sms_autofill: 1.3.1 
  flutter_rating_bar: ^4.0.0
  photo_view: ^0.11.1
 # ////////// BookKing Packages //////////
  sqflite: ^2.0.0+2
  shared_preferences: ^0.5.12+4
  share: ^0.6.5+4
  launch_review: ^3.0.1
  screen: ^0.0.5
  flutter_material_color_picker: ^1.0.5

 # ////////// Vpn Packages //////////

  line_icons: ^2.0.1
  ndialog: ^4.0.0+1

 # ////////// Music Packages //////////
  sliding_up_panel: ^1.0.2
  audioplayers: ^0.17.4
  assets_audio_player: 2.0.15
  dio: 4.0.0

 # ////////// NewsApp Packages //////////  
  cached_network_image: ^2.3.2+1
  path_drawing: ^0.4.1
  # provider: 4.0.4
  video_player: ^0.10.8+1

  # ////////// CryptoTech Packages //////////

  file_picker: ^3.0.1
  flutter_html: 
  path_provider: 
  websafe_svg: 

  # ////////// eStudy Packages ////////// 
  
  pin_input_text_field: 
  # flick_video_player: 
  wakelock: 

  # ////////// Food Master Packages ////////// 

 
  image: ^2.1.4
 
  #search address
  # rxdart: ^0.24.0
  google_maps_webservice: ^0.0.16
  flutter_google_places: ^0.2.8


  #stripe_payment: 1.0.9
  # stripe_payment: ^1.0.10

  #mollie payment
  mollie: any

  #notification
  # onesignal_flutter: ^2.2.0

  #map
  # google_maps_flutter: any #in ios i added this line GMSServices.provideAPIKey("YOUR KEY HERE"), when u create firebase project then add ios api key from google console

  

  http: 0.13.1
  webview_flutter: 0.3.22+1
  
                                                              
  #firebaselogin
  firebase_auth: ^1.1.2                     
  firebase_core: ^1.1.0
  google_sign_in: 4.5.3
  apple_sign_in: 0.1.0
  flutter_facebook_login: 3.0.0

  #stripe
  stripe_payment: 1.0.10

  #paystack
  flutter_paystack: ^1.0.5

  #razorpay
  razorpay_flutter: ^1.2.5

  #paytm
  paytm: ^2.0.0

  #googlemap
  google_maps_flutter: ^2.0.2

  path: ^1.8.0

  #firebase cloudfirestore
  cloud_firestore: ^1.0.3
  
  #firebase realtime db
  firebase_database: ^6.1.1
  
  #admob
  # admob_flutter: ^1.0.1

  #youtube
  youtube_player_iframe: ^2.0.0
  location: 4.1.1
  firebase_dynamic_links: ^2.0.3
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  provider: ^4.3.3

  image_picker:
  
  charts_flutter: ^0.10.0


dependency_overrides:

  flutter_inappwebview: ^5.2.1+1
  
  http: ^0.12.2

  http_parser: ^4.0.0

  plugin_platform_interface: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/webapp/  
   
   
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/font/OpenSans-Light.ttf
          weight: 300 
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/font/OpenSans-ExtraBold.ttf
          weight: 800
    - family: MyFont
      fonts:
        - asset: assets/font/SFUIText-Regular.ttf
        - asset: assets/font/SFUIText-Bold.ttf
          weight: 700   
    - family: HelveticaNeue
      fonts:
        - asset: assets/font/HelveticaNeue.ttf           
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
