const String Register = 'Register';
const String Email = 'Email Address';
const String First = 'First Name';
const String Last = 'Last Name';
const String Mobile = 'Mobile Number';
const String Password = 'Password';
const String ConPassword = 'Confirm Password';
const String CreateAcc = 'Create Account';
const String CountryCodeLbl="Select country code";